/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjForm;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

 
/**
 *
 * @author abdelhady
 */
public class FormMain extends javax.swing.JFrame {
         
         
         Connection cn;
         ResultSet rs;
         Statement s;
         String dbURL;

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        label_surgery.setVisible(false);
        label_appointments.setVisible(false);
        jPanel6_surgeries.setVisible(false);
        jPanel6_appointments.setVisible(false);
        set_icon();
        try{
           dbURL = "jdbc:ucanaccess://c:\\patients_database.accdb";
           cn=DriverManager.getConnection(dbURL,"","");
           s=cn.createStatement();}
        catch(Exception enf )
        {
          JOptionPane.showMessageDialog(null, "Not connected to database");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        label_appointments = new javax.swing.JLabel();
        label_GENDER = new javax.swing.JLabel();
        label_ADDRESS = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_AGE = new javax.swing.JLabel();
        label_Name = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        label_surgery = new javax.swing.JLabel();
        jPanel6_surgeries = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_surgery = new javax.swing.JTable();
        jPanel6_appointments = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_appointment = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(59, 240, 240));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_appointments.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_appointments.setText("Appoinments");
        jPanel1.add(label_appointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));
        jPanel1.add(label_GENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 112, 25));

        label_ADDRESS.setToolTipText("");
        jPanel1.add(label_ADDRESS, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 316, 25));

        jLabel6.setText("ADDRESS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, 22));

        jLabel5.setText("GENDER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, 22));

        label_AGE.setToolTipText("");
        jPanel1.add(label_AGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 112, 25));

        label_Name.setToolTipText("");
        jPanel1.add(label_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 247, 25));

        jTextField1.setToolTipText("");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 189, -1));

        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel3.setText("Patient ID");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 22));

        jLabel4.setText("AGE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 22));

        jButton2.setText("Show Medical History");
        jButton2.setToolTipText("");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        label_surgery.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_surgery.setText("Surgeries");
        label_surgery.setToolTipText("");
        jPanel1.add(label_surgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        Table_surgery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Surgery Type", "Date", "Doctor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table_surgery.setColumnSelectionAllowed(true);
        Table_surgery.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Table_surgery.setEditingColumn(0);
        Table_surgery.setEditingRow(0);
        Table_surgery.setEnabled(false);
        Table_surgery.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Table_surgeryKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table_surgery);

        javax.swing.GroupLayout jPanel6_surgeriesLayout = new javax.swing.GroupLayout(jPanel6_surgeries);
        jPanel6_surgeries.setLayout(jPanel6_surgeriesLayout);
        jPanel6_surgeriesLayout.setHorizontalGroup(
            jPanel6_surgeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6_surgeriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel6_surgeriesLayout.setVerticalGroup(
            jPanel6_surgeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6_surgeriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6_surgeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 510, 390));

        Table_appointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Status", "Date", "Doctor", "Bill", "Bill due date", "Report"
            }
        ));
        Table_appointment.setEditingColumn(0);
        Table_appointment.setEditingRow(0);
        Table_appointment.setEnabled(false);
        jScrollPane2.setViewportView(Table_appointment);

        javax.swing.GroupLayout jPanel6_appointmentsLayout = new javax.swing.GroupLayout(jPanel6_appointments);
        jPanel6_appointments.setLayout(jPanel6_appointmentsLayout);
        jPanel6_appointmentsLayout.setHorizontalGroup(
            jPanel6_appointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(jPanel6_appointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6_appointmentsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6_appointmentsLayout.setVerticalGroup(
            jPanel6_appointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(jPanel6_appointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6_appointmentsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(jPanel6_appointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 730, 390));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjForm/health_insurance_plans_of_florida.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 650));

        jTabbedPane1.addTab("SEARCH PATIENTS", jPanel1);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjForm/departments.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("DEPARTMENTS", jPanel2);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjForm/appointments.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("APPOINTMENTS", jPanel4);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjForm/surgeries.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SURGERIES", jPanel3);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjForm/Hospital_Staff.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("STAFF RECORD", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayPatientData(){
        
    try
        {
            
         
         //PatientID = (this.jTextField1.getText());
            
           rs= s.executeQuery("SELECT PATIENT.PATIENT_SSN, PATIENT.PATIENT_NAME, PATIENT.PATIENT_AGE, PATIENT.PATIENT_GENDER, PATIENT.PATIENT_ADDRESS\n" +
"FROM PATIENT\n" +
"WHERE (((PATIENT.PATIENT_SSN)="
                   + (this.jTextField1.getText())
                   + "))");
          
           
           if(!rs.isBeforeFirst()){
               Toolkit.getDefaultToolkit().beep();
               JOptionPane.showMessageDialog( null, "Patient id is not on the database", "Error", JOptionPane.ERROR_MESSAGE);
           }
             while(rs.next()){
             this.label_Name.setText(rs.getString(2));
             this.label_AGE.setText(rs.getString(3));
             this.label_GENDER.setText(rs.getString(4));
             this.label_ADDRESS.setText(rs.getString(5));
             
        }
                         rs=null;

    }
    catch(Exception enf ){
        
        JOptionPane.showMessageDialog(null, "Error");
    }

    }
    
    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+evt.getKeyChar());
    }//GEN-LAST:event_formKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       jTextField1.requestFocus(); 
    }//GEN-LAST:event_formKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        DisplayPatientData();
        jTextField1.selectAll();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        jTextField1.requestFocusInWindow();
        jTextField1.selectAll();
    }//GEN-LAST:event_jButton1MouseReleased

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            DisplayPatientData();
            jTextField1.selectAll();

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void Table_surgeryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_surgeryKeyPressed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+evt.getKeyChar());
        jTextField1.requestFocus();
    }//GEN-LAST:event_Table_surgeryKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JTableHeader th = Table_surgery.getTableHeader();
        try
        {

            rs= s.executeQuery("SELECT SURGERY_TYPE.SURGERY_NAME, PATIENT_SURGERY.PATIENTSURGERY_DATE, DOCTOR.DOCTOR_NAME, SURGERY_TYPE.SURGERY_RECOVERY_PERIOD\n" +
                "FROM SURGERY_TYPE INNER JOIN (PATIENT INNER JOIN (DOCTOR INNER JOIN PATIENT_SURGERY ON DOCTOR.DOCTOR_SSN = PATIENT_SURGERY.PATIENTSURGERY_DOCTORID) ON PATIENT.PATIENT_SSN = PATIENT_SURGERY.PATIENTSURGERY_PATIENT_ID) ON SURGERY_TYPE.SURGERY_ID = PATIENT_SURGERY.PATIENTSURGERY_SURGERY_TYPE_ID\n" +
                "WHERE (((PATIENT.PATIENT_SSN)="
                +(this.jTextField1.getText())
                +"));");
                    label_surgery.setVisible(true);
        label_appointments.setVisible(true);
        jPanel6_surgeries.setVisible(true);
        jPanel6_appointments.setVisible(true);
            Table_surgery.setModel(DbUtils.resultSetToTableModel(rs));

            Table_surgery.getColumnModel().getColumn(0).setHeaderValue("Type");
            Table_surgery.getColumnModel().getColumn(1).setHeaderValue("Date");
            Table_surgery.getColumnModel().getColumn(2).setHeaderValue("Doctor");
            Table_surgery.getColumnModel().getColumn(3).setHeaderValue("Recovery period");
            rs= s.executeQuery("SELECT APPOINTMENT.APPOINTMENT_STATUS, APPOINTMENT.APPOINTMENT_DATE, DOCTOR.DOCTOR_NAME, BILL.BILL_AMOUNT, BILL.BILL_DUE_DATE, APPOINTMENT.APPOINTMENT_Report\n" +
                "FROM PATIENT INNER JOIN (DOCTOR INNER JOIN (APPOINTMENT INNER JOIN BILL ON APPOINTMENT.APPOINTMENT_ID = BILL.BILL_APPOINTMENT_ID) ON DOCTOR.DOCTOR_SSN = APPOINTMENT.APPOINTMENT_DOCTORID) ON PATIENT.PATIENT_SSN = APPOINTMENT.APPOINTMENT_PATIENTID\n" +
                "WHERE (((PATIENT.PATIENT_SSN)="
                +(this.jTextField1.getText())
                +"));");

            Table_appointment.setModel(DbUtils.resultSetToTableModel(rs));
            Table_appointment.getColumnModel().getColumn(0).setHeaderValue("Status");
            Table_appointment.getColumnModel().getColumn(1).setHeaderValue("Date");
            Table_appointment.getColumnModel().getColumn(2).setHeaderValue("Doctor");
            Table_appointment.getColumnModel().getColumn(3).setHeaderValue("Amount");
            Table_appointment.getColumnModel().getColumn(4).setHeaderValue("Bill due date");
            Table_appointment.getColumnModel().getColumn(5).setHeaderValue("Report");
        }
        catch(Exception enf ){
            System.out.println(enf.getMessage());
            System.out.println("hager");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        jTextField1.requestFocusInWindow();
        jTextField1.selectAll();
    }//GEN-LAST:event_jButton2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_appointment;
    private javax.swing.JTable Table_surgery;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6_appointments;
    private javax.swing.JPanel jPanel6_surgeries;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_ADDRESS;
    private javax.swing.JLabel label_AGE;
    private javax.swing.JLabel label_GENDER;
    private javax.swing.JLabel label_Name;
    private javax.swing.JLabel label_appointments;
    private javax.swing.JLabel label_surgery;
    // End of variables declaration//GEN-END:variables

    private void set_icon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Untitled-2.png")));
    }
}
